### ISSUE TITLE
how you get decode?

### ISSUE THREAD

**Issue by Ko-Hon** [SydneyMatheus/rmtIrAcCtrl#1]
use Arduino? or esp-idf code?

**Comment by SydneyMatheus** [comment]
Hello,

To obtain the raw data from the air conditioning control, the Arduino IDE was used. The ESP-IDF was only used for data transmission. 

From the array of data obtained through the Arduino IDE, I interpreted them as on and off pulses, for example, poweroff[] = {3694, 1478, 518, 1314, 458, 1294, 478, 582, ...}, and this worked for my air conditioner. However, as I mentioned, it may not be a universal rule due to different encoding patterns implemented by various air conditioners, so it may not work in all cases. I haven't delved deep into understanding the specific encoding patterns used by these devices, and I also don't have an oscilloscope to visualize and interpret the waveforms of these remote controls.

Months later, revisiting this topic for another project, I noticed that the NEC protocol is very similar to the signal generated by AC remotes. If you want to understand the problem better, it might be interesting to research this protocol and see if it is indeed implemented in this scenario. Thank you for asking.
